# Generated by Django 5.2.2 on 2025-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(regular)', 'CSE(R)'), ('CSE(HONORS)', 'CSE(H)'), ('CSIT', 'CSIT')], max_length=100),
        ),
    ]
