# Generated by Django 5.2.2 on 2025-07-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(verbose_name='Faculty Type'),
        ),
    ]
